CREATE TYPE public.role AS ENUM ('admin', 'user', 'public');

CREATE TABLE public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  user_id UUID NOT NULL,
  type public.role NOT NULL DEFAULT 'public',
  email TEXT NULL,
  avatar_url TEXT NULL,
  phone TEXT NULL,
  details_complete BOOLEAN NULL DEFAULT FALSE,
  city TEXT NULL,
  street TEXT NULL,
  house_number TEXT NULL,
  first_name TEXT NULL,
  last_name TEXT NULL,
  postal_code TEXT NULL,
  purpose TEXT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id)
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to read their own data"
ON public.users
FOR SELECT
USING (user_id = auth.uid());

CREATE POLICY "Allow all users to insert"
ON public.users
FOR INSERT
WITH CHECK (true);